sudo: required

dist: xenial

services:
  - docker

env:
  matrix:
    - ARCH=amd64
    - ARCH=arm

language: bash

before_install:
  - mkdir -p ~/.docker
  - >
    echo '{ "experimental": "enabled" }' > ~/.docker/config.json
  - sudo systemctl restart docker
  - docker version

before_script:
  - >
    if [ "${ARCH}" = "arm" ]; then
      sed -ie 's/FROM alpine/FROM arm32v6\/alpine/g' 0.6/Dockerfile
      echo "Dockerfile modified"
    fi

script:
  - docker build --no-cache -t lnd --build-arg "goarch=${ARCH}" 0.6/
  - >
    if [ -n "${TRAVIS_TAG}" ]; then
      travis_retry timeout 5m echo "${DOCKER_PASS}" | docker login -u="${DOCKER_USER}" --password-stdin
      ./travis-deploy.sh "${ARCH}"
    fi
