name: Build branch

# Build on pushes to any branch, and PRs to `master` (hopefully it doesn't trigger on tag pushes…)
on:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    name: Build lnd
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        arch:
          - amd64
          - arm64
          - arm32v6
          - arm32v7

        ver:
          - 0.5
          - 0.6
          - 0.7
          - 0.8
          - 0.9

    env:
      DOCKER_BUILDKIT: 1
      APP: lnd
      VER_ARCH: "${{matrix.ver}}-${{matrix.arch}}"

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Verify all patches apply cleanly
        run: ./scripts/verify-patches.sh "${{matrix.ver}}"

      - name: Setup environment
        if: matrix.arch != 'amd64'
        run: |
          GOARCH="$(echo "${{matrix.arch}}" | grep -oE 'arm(64)?')"
          echo ::set-env name=GOARCH::"${GOARCH}"

          GOARM="$(echo "${{matrix.arch}}" | grep arm32 | tail -c 2)"
          echo ::set-env name=GOARM::"${GOARM}"

      - name: Build lnd:${{matrix.ver}}-${{matrix.arch}}
        run: |
          ARCH="${{matrix.arch}}"
          if [[ "${{matrix.arch}}" == "arm64" ]]; then
            ARCH="arm64v8"
          fi

          docker build --no-cache "${{matrix.ver}}/" \
            --build-arg "ARCH=${ARCH}" \
            --build-arg "GOARCH=${GOARCH}" \
            --build-arg "GOARM=${GOARM}" \
            --tag       "${APP}:${VER_ARCH}"

      - name: Show built image details
        run: docker images "${APP}"

      - name: Save image to a .tgz file
        run: |
          mkdir -p image/
          docker save "${APP}:${VER_ARCH}" | gzip > "image/${APP}-${VER_ARCH}.tgz"

      - name: Print sha256sum of produced Docker image
        run: sha256sum "image/${APP}-${VER_ARCH}.tgz"

      - name: Add Docker image as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-images
          path: image/

      - name: Extract binaries from the built image
        run: |
          mkdir -p bins/ binaries/
          ID=$(docker create "${APP}:${VER_ARCH}")
          docker cp  "${ID}:/usr/local/bin/${APP}"  bins/
          docker cp  "${ID}:/usr/local/bin/lncli"   bins/
          docker rm  "${ID}"

          # Compress both binaries into one archive
          tar  -C bins/  -cvaf "binaries/${APP}-${VER_ARCH}.tgz"  .

      - name: Print sha256sum of extracted binaries
        run: sha256sum bins/*

      - name: Add raw binaries as build artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binaries/

  test:
    name: Check sanity of images
    runs-on: ubuntu-18.04
    needs: build

    env:
      QEMU_VERSION: v4.2.0
      APP: lnd

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: docker-images

      - name: Print sha256sum of all Docker images
        run: sha256sum docker-images/*

      - name: Register self-compiled qemu
        run: docker run --rm --privileged "meedamian/simple-qemu:${QEMU_VERSION}" -p yes

      - name: Load all images locally
        run: ls -d docker-images/* | xargs -I %  docker load -i "%"

      - name: List all tagged images
        run: docker images "${APP}"

      - name: Run sanity checks
        env:
          DIR: /usr/local/bin
        run: |
          for tag in $(docker images "${APP}" --format "{{.Tag}}"); do
            echo
            echo "~~~~~ ${APP}:${tag} ~~~~~"
            docker inspect "${APP}:${tag}" | jq '.'

            docker run --rm                         "${APP}:${tag}" --version
            docker run --rm --entrypoint=lncli      "${APP}:${tag}" --version

            docker run --rm --entrypoint=uname      "${APP}:${tag}" -a
            docker run --rm --entrypoint=cat        "${APP}:${tag}" /etc/os-release
            docker run --rm --entrypoint=sha256sum  "${APP}:${tag}" ${DIR}/${APP} ${DIR}/lncli

            docker run --rm --entrypoint=sh -u=root "${APP}:${tag}" -c "apk add --no-cache file && file ${DIR}/${APP} ${DIR}/lncli"
          done
