name: Build & test on any push

on: push

jobs:
  build:
    name: Build lnd
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        ver:
          - 0.5
          - 0.6
          - 0.7

        arch:
          - amd64
          - arm64
          - arm32v6
          - arm32v7

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Set target platform
        if: matrix.arch != 'amd64'
        run: ./scripts/ci-set-target-image-architecture.sh "${{ matrix.arch }}" "${{ matrix.ver }}/Dockerfile"

      - name: Build invoicer in Docker
        run: >
          DOCKER_BUILDKIT=1 docker build --no-cache "${{ matrix.ver }}"
          --build-arg "goarch=${{ matrix.arch }}"
          --tag       "lnd:${{ matrix-ver }}-${{ matrix.arch }}"
          --file      "${{ matrix.ver }}/Dockerfile"

      - name: Show built image details
        run: docker images lnd

      - name: Save image to a .tgz file
        run: |
          mkdir -p image/
          docker save "lnd:${{ matrix.arch }}" | gzip > "image/lnd-${{ matrix.ver }}-${{ matrix.arch }}.tgz"

      - name: Print sha256sum of produced Docker image
        run: sha256sum "image/lnd-${{ matrix.ver }}-${{ matrix.arch }}.tgz"

      - name: Add Docker image as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: docker-images
          path: image/


      # TODO: see where the built binaries end up in the image
      - name: Extract binary from the built image
        run: |
          mkdir -p binary/
          ID=$(docker create "lnd:${{ matrix.arch }}")
          docker cp  "${ID}:/bin/lnd"    binary/
          docker cp  "${ID}:/bin/lncli"  binary/
          docker rm  "${ID}"

          # TODO: Two files so also tar is needed
          gzip -S "-${{ matrix.arch }}.gz" binary/lnd

      - name: Print sha256sum of extracted binary
        run: sha256sum binary/*

      - name: Add raw binary as build artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: binaries
          path: binary/
